apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort # exposes nodePort to external users
  ports:
  - port: 8080 
    nodePort: 30001  # port on the node
    targetPort: 8080 #port on container
    protocol: TCP
  selector:
    app: hello-world